version: '2'
services:
  nginx-proxy:
      image: jwilder/nginx-proxy
      container_name: nginx-proxy
      ports:
        - '80:80'
      volumes:
        - '/var/run/docker.sock:/tmp/docker.sock:ro'
  mariadb:
    image: 'bitnami/mariadb:latest'
    ports:
      - '3307:3306'
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
  application:
    image: 'bitnami/wordpress:latest'
    environment:
      VIRTUAL_HOST: wp.lo
    #ports:
     # - '81:80'
      #- '444:443'
    volumes:
      - 'wordpress_data:/bitnami/wordpress'
      - 'apache_data:/bitnami/apache'
      - 'php_data:/bitnami/php'
    depends_on:
      - mariadb
  pma:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mariadb
    #ports:
     # - 8181:80
    environment:
      VIRTUAL_HOST: pma.lo
      PMA_HOST: mariadb
      PMA_USER: root
      PMA_PASSWORD: ''
volumes:
  mariadb_data:
    driver: local
  wordpress_data:
    driver: local
  apache_data:
    driver: local
  php_data:
    driver: local
