version: '2'
services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
    environment:
      MARIADB_USER: root
      MARIADB_PASSWORD: password
  application:
    image: 'bitnami/wordpress:latest'
    ports:
      - '81:80'
      - '444:443'
    volumes:
      - 'wordpress_data:/bitnami/wordpress'
      - 'apache_data:/bitnami/apache'
      - 'php_data:/bitnami/php'
    depends_on:
      - mariadb
  pma:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mariadb
    ports:
      - 8181:80
    environment:
      PMA_HOST: mariadb
      PMA_USER: root
      PMA_PASSWORD: ''
volumes:
  mariadb_data:
    driver: local
  wordpress_data:
    driver: local
  apache_data:
    driver: local
  php_data:
    driver: local
